name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Trigger on pushes to the main branch
  pull_request:
    branches: ["main"] # Also run on pull requests to main for build checks
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub UI

# Permissions required for GitHub Pages deployment (placed at the top level)
permissions:
  contents: read    # To checkout your repository code
  pages: write      # To deploy to GitHub Pages
  id-token: write   # Crucial for OIDC authentication with GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permissions defined at workflow level will apply here.
    # No need to repeat the permissions block here unless you need job-specific overrides.

    strategy:
      matrix:
        node-version: [24.x] # Use Node.js 24.x as requested

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: npm install

      - name: Build project with Vite
        run: npm run build # This executes "tsc && vite build" from your package.json

      - name: Setup Pages
        uses: actions/configure-pages@v5 # Configures the environment for GitHub Pages
        
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3 # Uploads the build output
        with:
          path: './dist' # Vite's default output directory for production builds

  deploy:
    environment:
      name: github-pages # Specifies the deployment environment
      url: ${{ steps.deployment.outputs.page_url }} # Provides the URL to the deployed site
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    
    # Permissions defined at workflow level will apply here.
    # No need to repeat the permissions block here.

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Deploys the uploaded artifact
